# EDA and User Generation

In [3]:
import pandas as pd
import numpy as np
import random

## Music Metadata

In [31]:
df = pd.read_csv("metadata.csv", header = 0)

In [32]:
df.head()

,id,name,album,album_id,artists,artist_ids,track_number,disc_number,explicit,danceability,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,year,release_date
0,7lmeHLHBe4nmXzuXc0HDjk,Testify,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,['Rage Against The Machine'],['2d0hyoQ5ynDBnkvAbJKORj'],1,1,False,0.470,...,0.0727,0.02610,0.000011,0.3560,0.503,117.906,210133,4.0,1999,1999-11-02
1,1wsRitfRRtWyEapl0q22o8,Guerrilla Radio,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,['Rage Against The Machine'],['2d0hyoQ5ynDBnkvAbJKORj'],2,1,True,0.599,...,0.1880,0.01290,0.000071,0.1550,0.489,103.680,206200,4.0,1999,1999-11-02
2,1hR0fIFK2qRG3f3RF70pb7,Calm Like a Bomb,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,['Rage Against The Machine'],['2d0hyoQ5ynDBnkvAbJKORj'],3,1,False,0.315,...,0.4830,0.02340,0.000002,0.1220,0.370,149.749,298893,4.0,1999,1999-11-02
3,2lbASgTSoDO7MTuLAXlTW0,Mic Check,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,['Rage Against The Machine'],['2d0hyoQ5ynDBnkvAbJKORj'],4,1,True,0.440,...,0.2370,0.16300,0.000004,0.1210,0.574,96.752,213640,4.0,1999,1999-11-02
4,1MQTmpYOZ6fcMQc56Hdo7T,Sleep Now In the Fire,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,['Rage Against The Machine'],['2d0hyoQ5ynDBnkvAbJKORj'],5,1,False,0.426,...,0.0701,0.00162,0.105000,0.0789,0.539,127.059,205600,4.0,1999,1999-11-02

In [34]:
df.shape

(1204025, 24)

## User Generation

In [64]:
def generate_user_item(song_df, num_users=500, min_tracks=10, max_tracks=50, max_plays=20):
    user_item_data = []
    track_ids = song_df['id'].dropna().unique()

    for user_index in range(1, num_users + 1):
        user_id = user_index
        n_tracks = random.randint(min_tracks, max_tracks)
        listened_tracks = np.random.choice(track_ids, size=n_tracks, replace=False)

        for track_id in listened_tracks:
            play_count = random.randint(1, max_plays)
            user_item_data.append({
                'user_id': user_id,
                'track_id': track_id,
                'play_count': play_count
            })

    return pd.DataFrame(user_item_data)

In [65]:
user_item_df = generate_user_item(df, num_users=1000)

user_item_df.to_csv("user_item.csv", index=False)

In [66]:
user_item_df.head()

   user_id                track_id  play_count
0        1  0vcV9S5LPMcAQZuxmvc8sE          14
1        1  1g5ZSaN2JBegmWwvKAEawZ           4
2        1  0MbIWHZ5ojkbWHfgKjrx23          20
3        1  3mXol3KLx3Q1RxVNLE1OJa           4
4        1  1K3OAJ09NrsXv4DCsPlYvQ           8